# Generated by Django 5.1.5 on 2025-01-31 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Member',
            new_name='Coordinates',
        ),
    ]
