# Generated by Django 5.1.5 on 2025-02-01 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_rename_member_coordinates'),
    ]

    operations = [
    ]
