# Generated by Django 5.1.5 on 2025-02-01 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_school_delete_coordinates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=14, null=True),
        ),
    ]
