# Generated by Django 5.1.5 on 2025-02-01 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0005_alter_school_latitude_alter_school_longitude'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='latitude',
            new_name='lat',
        ),
        migrations.RenameField(
            model_name='school',
            old_name='longitude',
            new_name='lng',
        ),
    ]
