# Generated by Django 5.1.5 on 2025-02-01 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0006_rename_latitude_school_lat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=14, null=True),
        ),
    ]
