# Generated by Django 5.1.5 on 2025-02-01 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0007_alter_school_lat_alter_school_lng'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='lat',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='school',
            name='lng',
            field=models.FloatField(),
        ),
    ]
